language: c

sudo: false

services:
  - docker

cache:
  apt: true

script:
  - docker login --email="${DOCKER_EMAIL}" --username="${DOCKER_USERNAME}" --password="${DOCKER_PASSWORD}"
  - make

deploy:
  provider: script
  script: ./deploy.sh

notifications:
  email: true
