language: c

sudo: false

services:
  - docker

cache:
  apt: true

script:
  - docker login --email="${DOCKER_EMAIL}" --username="${DOCKER_USERNAME}" --password="${DOCKER_PASSWORD}"
  - make

after_success:
  - docker login --email="${DOCKER_EMAIL}" --username="${DOCKER_USERNAME}" --password="${DOCKER_PASSWORD}"
  - make push

notifications:
  email: true
